#!/bin/bash

sudo apt update && sudo apt upgrade

# Go
GO_LATEST_VERSION=$(curl -s https://go.dev/VERSION?m=text)

if [[ ! -x "$(command -v go)" || $(go env GOVERSION) != $GO_LATEST_VERSION ]]
then
  echo "Installing latest version of Go ..."
  GO_TARFILE="$GO_LATEST_VERSION.linux-amd64.tar.gz"
  wget "https://go.dev/dl/$GO_TARFILE"
  sudo rm -rf /usr/local/go
  sudo tar -C /usr/local -xzf $GO_TARFILE
  rm $GO_TARFILE*
else
  echo "Latest version of Go already installed."
fi

# Node & npm
NODE_LTS=16
echo "Installing nodejs and npm ..."
curl -sL https://deb.nodesource.com/setup_$NODE_LTS.x | sudo -E bash -
sudo apt install nodejs -y

# Neovim requierements
echo "Installing neovim dependencies ..."
sudo apt install xsel python3-pip pynvim ripgrep fd-find -y
sudo npm i -g neovim

# Packages
echo "Installing utilities packages ..."

aptPackages=( "zsh" "tree" )

for p in "${aptPackages[@]}"
do
  if ! [ -x "$(command -v $p)" ]; then
    echo "Installing $p ..."
    sudo apt install $p -y
  else
    echo "Package $p already installed ..."
  fi
done

sudo npm -i tldr

go install github.com/jesseduffield/lazygit@latest

# Set zsh as default terminal
chsh -s $(which zsh)

# Copy config files
cp .dotfiles/nvim ~/.config
cp .dotfile/zsh ~/.config
