#!/bin/bash
sudo apt update -y && sudo apt upgrade -y

# Copy config files
mkdir -p .config
cp -r .dotfiles/nvim ~/.config/
cp -r .dotfiles/zsh ~/.config/

# Go
GO_LATEST_VERSION=$(curl -s https://go.dev/VERSION?m=text)

if [[ ! -x "$(command -v go)" || $(go env GOVERSION) != $GO_LATEST_VERSION ]]
then
  echo "Installing latest version of Go ..."
  GO_TARFILE="$GO_LATEST_VERSION.linux-amd64.tar.gz"
  wget "https://go.dev/dl/$GO_TARFILE"
  sudo rm -rf /usr/local/go
  if [[ -x "$(command -v go)" ]]; then
	  sudo rm -rf $(which go)
  fi
  sudo tar -C /usr/local -xzf $GO_TARFILE
  rm $GO_TARFILE*
else
  echo "Latest version of Go already installed."
fi

# Node & npm
NODE_LTS=16
echo "Installing nodejs and npm ..."
curl -sL https://deb.nodesource.com/setup_$NODE_LTS.x | sudo -E bash -
sudo apt install nodejs -y

# Neovim requierements
echo "Installing neovim dependencies ..."
sudo apt install xsel ripgrep fd-find -y
sudo npm i -g neovim

# Utilities Packages
echo "Installing utilities packages ..."

aptPackages=( "zsh" "tree" "unzip")

for p in "${aptPackages[@]}"
do
  if ! [ -x "$(command -v $p)" ]; then
    echo "Installing $p ..."
    sudo apt install $p -y
  else
    echo "Package $p already installed ..."
  fi
done

sudo npm install -g tldr

/usr/local/go/bin/go install github.com/jesseduffield/lazygit@latest

# Set zsh as default terminal
sudo chsh -s $(which zsh)

